version: "3"

services:
  node:
    image: node:16.14
    container_name: car_shop
    build: ./
    command: bash -c "npm install && npm run dev"
    restart: always
    working_dir: /app
    platform: linux/x86_64
    volumes:
      - ./:/app
    depends_on:
      - mongodb
    ports:
      - 3001:3001
    # env_file:
    #   - ./.env
    environment:
      - MONGO_URI=mongodb://mongodb:27017/CarShop

  mongodb:
    image: mongo:5.0.7
    container_name: car_shop_db
    volumes:
      - ./:/app
    restart: always
    platform: linux/x86_64
    ports:
      - 27017:27017
    # env_file:
    #   - ./.env

networks:
  default:
    name: car_shop_net
